### ISSUE TITLE
Migrate your custom actions - no steps provided

### ISSUE THREAD

**Issue by dinobrago** [MicrosoftDocs/composer-docs#154]
[Enter feedback here]

This documentation does not actually provide any steps on how to migrate custom actions to Composer 2.0. 

I can find that the custom action has been deactivated. 

What actual steps do I need to take to reintegrate my custom action? 

Does this require changes to the code of the custom action?

Is there  a different block in Composer 2.0 that can be used to access the custom action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 681bbd54-b795-fec3-12ad-683e97f7b0c8
* Version Independent ID: 665da772-758f-8883-e83f-3885c691772e
* Content: [How to convert a Composer version 1.x bot to version 2.0 - Bot Framework Composer](https://docs.microsoft.com/en-us/composer/how-to-migrate-bot-to-2-0)
* Content Source: [composer-docs/how-to-migrate-bot-to-2-0.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-migrate-bot-to-2-0.md)
* Service: **bot-composer**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Agreed that we need to add information on what to do next. :(

I'll update the article, but in the meantime, you have 2-3 options, depending on how you count.
1. The feature might have been added to Composer since v1.4, in which case the custom action is no longer needed, but you still need to find the new feature. [What's new](https://docs.microsoft.com/composer/what-is-new) is hopefully your friend here.
2. The feature might be available through a component through the [package library](https://docs.microsoft.com/composer/concept-packages).
3. You may need to update your code and add your custom action back in. See [Create custom actions](https://docs.microsoft.com/composer/how-to-create-custom-actions) for the new instructions.

Hope that helps.

**Comment by JonathanFingold** [comment]
@dinobrago - The updated article is in review. Changes will likely be live in a week or two.
