### ISSUE TITLE
Missing step for testing

### ISSUE THREAD

**Issue by MCKRUZ** [MicrosoftDocs/composer-docs#52]
Once you select "test in Emulator" 

You actually have to select Open bot and paste in the URL before the bot will respond.  This is not evident according to this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1636bda0-c8ee-5632-bb87-d7972f87e9d7
* Version Independent ID: c8ab72b1-f10a-b0a7-1424-d86a6978621a
* Content: [Tutorial: Create a bot - Bot Composer](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-create-bot)
* Content Source: [composer-docs/tutorial/tutorial-create-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/tutorial/tutorial-create-bot.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment]
Hi, thanks for reporting the issue. Which Composer version did you use?
The current Composer documentation is consistent with [Composer 1.2.1 release](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.2.1). So if you are using 1.2.1 and previous versions, you should not have this issue. 
Please provide more details about the Composer version you were using so that we can better assist you. 
Thanks a lot!

**Comment by MCKRUZ** [comment]
ahhh wasn't composer, it was the emulator.  Updated that version and now is
working.

**Comment by zxyanliu** [comment]
@MCKRUZ Thanks for your response. 
Do you want to close the issue or do you want me to close it?

**Comment by MCKRUZ** [comment]
Yes can you close it

**Comment by zxyanliu** [comment]
Thanks again for your feedback! 
Closing the issue since it has been addressed.
